id: P94B0FEE8
initial_creation_type: input
source_metadata:
  title: Spandakārikā with the commentary by Kṣemarāja
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Śaiva
  data entry: Oliver Hellwig
  contribution to GRETIL: Oliver Hellwig
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:08:24.366924'
last_modified_at: '2022-03-09T15:08:24.366957'
